databases:
  - name: simargmbh-db
    databaseName: simargmbh
    user: simargmbh

services:
  - type: web
    name: simargmbh
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: "Attendance Management System"
      - key: APP_ENV
        value: "production"
      - key: APP_KEY
        value: "base64:oZeQtl191M1fElZxT9IdBUYJEWm401fQQ1z3BS7Tv5I="
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://simargmbh.onrender.com"
      - key: DB_CONNECTION
        value: "pgsql"
      - key: DB_HOST
        fromDatabase:
          name: simargmbh-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: simargmbh-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: simargmbh-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: simargmbh-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: simargmbh-db
          property: password
      - key: DB_SSLMODE
        value: "require"
      - key: CACHE_DRIVER
        value: "file"
      - key: QUEUE_CONNECTION
        value: "sync"
      - key: SESSION_DRIVER
        value: "file"
      - key: LOG_CHANNEL
        value: "stderr"
      - key: LOG_LEVEL
        value: "error"
